version: "3.8"
services:
  backend:
    build:
      context: ./backend
      target: dev  # Change to 'prod' for production
    image: loganal-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-db-data:/app/db
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      target: dev  # Change to 'prod' for production
    image: loganal-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  backend-db-data:
    driver: local
